project_id = "ernubxpsllxprtdylmcy"

[functions.fetch-inmet-data]
verify_jwt = false

[functions.fetch-inmet-stations]
verify_jwt = false

[functions.fetch-weather-data]
verify_jwt = false

[functions.fetch-nasa-power-data]
verify_jwt = false